import { parseScript } from "@/dsl/parser.ts"

const source = `VERSION 1.0
CANVAS 1920 1080
DEFINE stick PARAMS MOOD
  CREATE head AS CIRCLE
    POSITION 0 0
    RADIUS 24
  END
  LINE FROM 0 25 TO 0 95
  LINE FROM 0 45 TO -35 75
  LINE FROM 0 45 TO 35 75
  LINE FROM 0 95 TO -28 145
  LINE FROM 0 95 TO 28 145
  CREATE mood AS TEXT
    TEXT MOOD
    POSITION 50 -20
    SIZE 28
  END
END
DEFINE speech PARAMS TEXT
  CREATE bubble AS RECTANGLE
    POSITION 0 0
    WIDTH WIDTH
    HEIGHT HEIGHT
    FILL #FFFFFF
  END
  CREATE words AS TEXT
    TEXT TEXT
    POSITION 0 0
    MAXWIDTH MAXWIDTH
  END
END
DEFINE thought PARAMS TEXT
  CREATE cloud AS CIRCLE
    POSITION 0 0
    RADIUS 75
  END
  CREATE words AS TEXT
    TEXT TEXT
    POSITION 0 0
    MAXWIDTH 130
  END
  CREATE dot1 AS CIRCLE
    POSITION -45 95
    RADIUS 10
  END
  CREATE dot2 AS CIRCLE
    POSITION -65 122
    RADIUS 5
  END
END
DEFINE sticky PARAMS TEXT
  CREATE paper AS RECTANGLE
    POSITION 0 0
    WIDTH 220
    HEIGHT 180
    FILL #FFF2A6
  END
  CREATE words AS TEXT
    TEXT TEXT
    POSITION 0 0
    MAXWIDTH 190
  END
END
DEFINE badge PARAMS TEXT
  CREATE medal AS CIRCLE
    POSITION 0 0
    RADIUS 58
    FILL #F4C542
  END
  CREATE words AS TEXT
    TEXT TEXT
    POSITION 0 0
    SIZE 28
  END
END
DEFINE tick
  CREATE mark AS ICON
    NAME check
    POSITION 0 0
    SIZE 42
    COLOR #35A66F
  END
END
DEFINE brackets
  LINE FROM -40 -50 TO -65 -50
  LINE FROM -65 -50 TO -65 50
  LINE FROM -65 50 TO -40 50
  LINE FROM 40 -50 TO 65 -50
  LINE FROM 65 -50 TO 65 50
  LINE FROM 65 50 TO 40 50
END
DEFINE callout PARAMS TEXT
  CREATE box AS RECTANGLE
    POSITION 0 0
    WIDTH 250
    HEIGHT 110
  END
  CREATE words AS TEXT
    TEXT TEXT
    POSITION 0 0
    MAXWIDTH 210
  END
  LINE FROM -70 55 TO -100 95
END
DEFINE curvedarrow
  INK ARROW FROM -100 50 TO 100 -50
END
DEFINE timeline
  LINE FROM -200 0 TO 200 0
  CREATE start AS CIRCLE
    POSITION -200 0
    RADIUS 12
  END
  CREATE finish AS CIRCLE
    POSITION 200 0
    RADIUS 12
  END
END
DEFINE progress PARAMS VALUE
  CREATE ring AS CIRCLE
    POSITION 0 0
    RADIUS 70
    DRAW 1s
  END
  CREATE percent AS TEXT
    TEXT VALUE
    POSITION 0 0
    SIZE 40
  END
END
DEFINE checklist PARAMS TEXT
  USE tick AS checked AT -100 0
  CREATE item AS TEXT
    TEXT TEXT
    POSITION 30 0
  END
END
SCENE 0
END SCENE
`

export const BUILTIN_MACROS = parseScript(source).ast.macros
